使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)  # 生成长度为10的一维数组

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = open("x.pkl", "wb")  # 打开文件操作，和python并无区别

In [5]:
pickle.dump(x, f)  # 使用pickle把数组x给他dump到f中

In [6]:
!ls  # 查看目录下多出了一个x.pkl文件

Applications                 access.log
Array.ipynb                  access_clean.log
Array的inout和output.ipynb   anaconda
Desktop                      derby.log
Documents                    index.html
Downloads                    metastore_db
Library                      part-00001
Movies                       seaborn-data
Music                        x.pkl
Pictures                     数组与矩阵运算.ipynb
Public


In [7]:
f = open("x.pkl", "rb")  # 读取x.pkl文件

In [8]:
pickle.load(f)  # 通过pickle查看

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

使用numpy序列化array到硬盘

In [9]:
np.save("one_array", x)  

In [10]:
!ls

Applications                 access.log
Array.ipynb                  access_clean.log
Array的inout和output.ipynb   anaconda
Desktop                      derby.log
Documents                    index.html
Downloads                    metastore_db
Library                      one_array.npy
Movies                       part-00001
Music                        seaborn-data
Pictures                     x.pkl
Public                       数组与矩阵运算.ipynb


In [11]:
np.load("one_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = np.arange(20)

In [13]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.savez("two_array.npz", a=x, b=y)  # 通过numpy的savez把两个数组保存到一个npz压缩文件中，并分别取名为a，b

In [15]:
!ls  # 目录下多出two_array.npz的压缩文件

Applications                 access_clean.log
Array.ipynb                  anaconda
Array的inout和output.ipynb   derby.log
Desktop                      index.html
Documents                    metastore_db
Downloads                    one_array.npy
Library                      part-00001
Movies                       seaborn-data
Music                        two_array.npz
Pictures                     x.pkl
Public                       数组与矩阵运算.ipynb
access.log


In [16]:
c = np.load("two_array.npz")  # 读取two_array.npz压缩文件

In [17]:
c["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
c["b"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])