一、数组的创建和访问

In [2]:
import numpy as np

In [3]:
# 创建python的list
list_1 = [1,2,3,4]

In [4]:
list_1

[1, 2, 3, 4]

In [5]:
array_1 = np.array(list_1)

In [6]:
array_1

array([1, 2, 3, 4])

In [7]:
list_2 = [5,6,7,8]

In [8]:
array_2 = np.array([list_1, list_2])

In [9]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
array_2.shape  # 显示array_2的属性（输出表示数组array_2是一个2行4列的数组）

(2, 4)

In [11]:
array_2.size  # 返回数组里面元素个数

8

In [12]:
array_2.dtype  # 返回数组里面元素的类型

dtype('int64')

In [17]:
array_3 = np.arange(1, 10, 2)  # 与python原本的用法基本一致

In [18]:
array_3

array([1, 3, 5, 7, 9])

In [19]:
np.zeros(5)  # 返回一个一维全零矩阵

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
np.zeros([2,3])  # 返回一个二维全零矩阵

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.eye(5)  # 返回一个5*5的单位矩阵，数组元素为float类型

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
# 数组的访问
a = np.arange(1,10)

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[1]  # 与python一致

2

In [25]:
a[1:5]  #与python一致

array([2, 3, 4, 5])

In [26]:
b = np.array([[1,2,3],[4,5,6]])

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b[1][0]  # 访问二维数组索引也是从0开始

4

In [29]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
c[:2, 1:]  # :2表示从第0行到第1行访问数据，后面:1表示从每一行第1个元素开始取直到最后一个元素

array([[2, 3],
       [5, 6]])