In [1]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series([1,2,3,4])  # 创建series

In [4]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
s1.values  # 查看series的值

array([1, 2, 3, 4])

In [6]:
s1.index  # 查看series的索引

RangeIndex(start=0, stop=4, step=1)

In [7]:
s2 = pd.Series(np.arange(10))  # 创建一个长度为10的series

In [8]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [9]:
s3 = pd.Series({'1':1,'2':2,'3':3})  # 通过python字典创建series

In [10]:
s3

1    1
2    2
3    3
dtype: int64

In [11]:
s3.values

array([1, 2, 3])

In [12]:
s3.index

Index(['1', '2', '3'], dtype='object')

In [13]:
s4 = pd.Series([1,2,3,4], index=['a','b','c','d'])  # 创建series并设置索引index

In [14]:
s4

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
s4.values

array([1, 2, 3, 4])

In [16]:
s4.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [17]:
s4['a']  # 查询series中的值

1

In [18]:
s4[s4>2]  # 按条件查询series中的值

c    3
d    4
dtype: int64

In [19]:
s4.to_dict()  # 把series转换成dict

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [20]:
s5 = pd.Series(s4.to_dict())

In [21]:
s5

a    1
b    2
c    3
d    4
dtype: int64

In [47]:
# 索引超出数据范围情况下的显示
index_1 = ['a','b','c','d','e']
s6 = pd.Series(s5, index=index_1)

In [48]:
s6

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [49]:
pd.isnull(s6)  # 找出为NaN的数据位置

a    False
b    False
c    False
d    False
e     True
dtype: bool

In [50]:
pd.notnull(s6)# 找出不为NaN的数据位置

a     True
b     True
c     True
d     True
e    False
dtype: bool

In [51]:
s6

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [52]:
s6.name = 'demo'  # 给series起名字

In [53]:
s6

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
Name: demo, dtype: float64

In [54]:
s6.index.name = 'demo index'  # 给series的索引起名字

In [56]:
s6

demo index
a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
Name: demo, dtype: float64

In [57]:
s6.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object', name='demo index')

In [58]:
s6.values

array([  1.,   2.,   3.,   4.,  nan])