快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)  # randn创建一个长度为10的一维数组，并且数组里面的值符合标准正态分布

array([ 0.48117846, -1.58480676,  0.28558744,  1.59817834, -0.50307612,
       -0.68677985,  0.63813199, -1.1281135 ,  0.50025852, -0.89556997])

In [3]:
np.random.randint(10)  # 输出10以内随机一个数字

5

In [6]:
np.random.randint(10)  # 输出10以内随机一个数字

2

In [8]:
np.random.randint(10, size=(2,3))  # 创建2*3的数组，数组元素是10以内随机数字

array([[8, 1, 5],
       [7, 6, 0]])

In [9]:
np.random.randint(10, size=20)  # 创建长度为20的数组，数组元素是10以内随机数字

array([6, 7, 8, 7, 7, 1, 1, 7, 2, 1, 0, 1, 7, 5, 7, 8, 5, 7, 4, 0])

In [10]:
np.random.randint(10, size=20).reshape(4,5)  # 创建长度为20的数组，然后做reshape操作把它变为4*5的数组，数组元素是10以内随机数字

array([[2, 2, 8, 4, 6],
       [1, 0, 4, 4, 0],
       [3, 9, 7, 1, 1],
       [1, 7, 0, 4, 8]])

数组运算

In [11]:
a = np.random.randint(10, size=20).reshape(4,5) 

In [12]:
b = np.random.randint(10, size=20).reshape(4,5) 

In [13]:
a

array([[8, 7, 3, 7, 8],
       [4, 1, 1, 4, 3],
       [5, 4, 6, 0, 7],
       [1, 4, 9, 4, 0]])

In [14]:
b

array([[6, 6, 8, 2, 2],
       [5, 1, 7, 0, 2],
       [8, 3, 8, 2, 4],
       [4, 2, 6, 0, 1]])

In [15]:
# 数组加法
a + b

array([[14, 13, 11,  9, 10],
       [ 9,  2,  8,  4,  5],
       [13,  7, 14,  2, 11],
       [ 5,  6, 15,  4,  1]])

In [16]:
# 数组减法
a - b

array([[ 2,  1, -5,  5,  6],
       [-1,  0, -6,  4,  1],
       [-3,  1, -2, -2,  3],
       [-3,  2,  3,  4, -1]])

In [17]:
# 数组乘法
a*b

array([[48, 42, 24, 14, 16],
       [20,  1,  7,  0,  6],
       [40, 12, 48,  0, 28],
       [ 4,  8, 54,  0,  0]])

In [18]:
# 数组除法 如果出现分母为0，就会报警
a/b 

/Users/chandler/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[ 1.33333333,  1.16666667,  0.375     ,  3.5       ,  4.        ],
       [ 0.8       ,  1.        ,  0.14285714,         inf,  1.5       ],
       [ 0.625     ,  1.33333333,  0.75      ,  0.        ,  1.75      ],
       [ 0.25      ,  2.        ,  1.5       ,         inf,  0.        ]])

创建矩阵

In [20]:
np.mat([[1,2,3],[4,5,6]]) # 创建一个二维矩阵

matrix([[1, 2, 3],
        [4, 5, 6]])

In [21]:
# 把数组a转换成矩阵
np.mat(a)

matrix([[8, 7, 3, 7, 8],
        [4, 1, 1, 4, 3],
        [5, 4, 6, 0, 7],
        [1, 4, 9, 4, 0]])

矩阵运算

In [22]:
A = np.mat(a)

In [25]:
A

matrix([[8, 7, 3, 7, 8],
        [4, 1, 1, 4, 3],
        [5, 4, 6, 0, 7],
        [1, 4, 9, 4, 0]])

In [23]:
B = np.mat(b)

In [26]:
B

matrix([[6, 6, 8, 2, 2],
        [5, 1, 7, 0, 2],
        [8, 3, 8, 2, 4],
        [4, 2, 6, 0, 1]])

In [24]:
# 矩阵加法
A + B

matrix([[14, 13, 11,  9, 10],
        [ 9,  2,  8,  4,  5],
        [13,  7, 14,  2, 11],
        [ 5,  6, 15,  4,  1]])

In [27]:
# 矩阵减法
A - B

matrix([[ 2,  1, -5,  5,  6],
        [-1,  0, -6,  4,  1],
        [-3,  1, -2, -2,  3],
        [-3,  2,  3,  4, -1]])

In [28]:
# 矩阵乘法
A * B
# 这里报错了，因为矩阵相乘必须满足A的行与B的列个数相等才行，下面就重新创建两个矩阵

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [29]:
C = np.mat(np.random.randint(10, size=20).reshape(4,5))  # 4行5列
D = np.mat(np.random.randint(10, size=20).reshape(5,4))  # 5行4列

In [30]:
C

matrix([[0, 5, 4, 2, 3],
        [2, 9, 7, 7, 3],
        [3, 3, 3, 8, 6],
        [5, 7, 0, 8, 0]])

In [31]:
D

matrix([[0, 3, 5, 6],
        [7, 0, 7, 1],
        [6, 2, 4, 9],
        [6, 2, 7, 0],
        [6, 3, 4, 2]])

In [42]:
# 矩阵乘法
C*D

matrix([[ 89,  21,  77,  47],
        [165,  43, 162,  90],
        [123,  49, 128,  60],
        [ 97,  31, 130,  37]])

Array常用函数

In [33]:
a = np.random.randint(10, size=20).reshape(5,4)

In [34]:
np.unique(a) # 返回数组a里面那些元素是唯一的

array([0, 1, 2, 3, 4, 5, 6, 9])

In [35]:
a

array([[3, 6, 3, 4],
       [0, 0, 9, 0],
       [6, 3, 9, 6],
       [5, 5, 2, 9],
       [9, 6, 9, 1]])

In [36]:
sum(a)  # 数组a每一列的和

array([23, 20, 32, 20])

In [37]:
sum(a[0])  # 计算数组a第一行元素之和

16

In [38]:
sum(a[:, 0])  # 计算第一列的和 

23

In [39]:
a.max()  # 查看数组a里面的最大元素值

9

In [40]:
max(a[0])  # 查看数组a第一行最大值

6

In [41]:
max(a[:, 0])  # 查看数组a第一列最大值

9